[project]
name = "stacks-inscription-proto"
requirements = []
[contracts.inscription-v4]
path = "contracts/inscription-v4.clar"
clarity_version = 2
epoch = 2.4

[contracts.u64bxr-v3]
path = "contracts/u64bxr-v3.clar"
clarity_version = 2
epoch = 2.4
