[project]
name = 'xStrata'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = 2.5


# Add every other contract so Clarinet checks them too
[contracts.u64bxr-v11-2]
path = 'contracts/u64bxr-v11.2.clar'
clarity_version = 4
epoch = 'latest'


[repl.analysis]
passes = [
  'call_checker',
  'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
